const experiences = [
  {
    id: 1,
    title: 'Fullstack Developer',
    company: 'Freelance',
    description: 'I work at Freelance in Feb 1, 2023 as Full stack developer.',
    durationStart: 'Feb 2023',
    durationEnd: 'Now',
    skills: [
      'Javascript',
      'Typescript',
      'React.js',
      'Redux',
      'Next.js',
      'Node.js',
      'Express.js',
      'MongoDB',
      'Postgresql',
    ],
    logo: 'https://afyxxqlmftohiygrtfjm.supabase.co/storage/v1/object/public/projects/company-logo/linkedin_3536505.png',
  },
  {
    id: 2,
    title: 'Frontend Developer',
    company: 'Myanmar Media Linkage',
    companyLink: 'https://mml.com.mm/',
    description:
      'I work at Myanmar Media Linkage  in November 1, 2023 as Frontend developer.',
    durationStart: 'Nov 2023',
    durationEnd: 'Mar',
    skills: ['Typescript', 'React.js', 'Redux', 'Next.js', 'Next-Auth'],
    logo: 'https://afyxxqlmftohiygrtfjm.supabase.co/storage/v1/object/public/projects/company-logo/cropped-MML_icon-192x192.png',
  },
  {
    id: 3,
    title: 'Fullstack Developer',
    company: 'Walmal Ecommerce',
    description:
      'I work at Freelance in April 1, 2024 as Full stack developer.',
    durationStart: 'April 1',
    durationEnd: 'Now',
    skills: [
      'Javascript',
      'Typescript',
      'React.js',
      'Redux',
      'Next.js',
      'Node.js',
      'Express.js',
      'MongoDB',
      'Postgresql',
    ],
    logo: 'https://afyxxqlmftohiygrtfjm.supabase.co/storage/v1/object/public/projects/company-logo/rsz_walmalpng%20(1).png',
  },
];
export default experiences;
