export const projects = [
  {
    id: 1,
    title: 'Edu Pad',
    description: 'Our ReactJS-powered Udemy-like platform',
    demo: '',
    image: '1708015174003Screenshot from 2024-02-15 23-03-41.png',
    skills: ['js', 'react', 'redux', 'php', 'laravel', 'mysql'],
    made_at: 'Freelance',
    year: 2023,
  },
  {
    id: 2,
    title: 'SUPA Blog',
    description: 'Blogging Web Application with supabase',
    demo: 'https://supablogr.vercel.app',
    image: '1703784844823supablog.jpg',
    skills: ['js', 'react', 'redux', 'supabase'],
    made_at: '',
    year: 2023,
  },
  {
    id: 3,
    title: 'JK Mobile',
    description: 'Mini Mobile shop',
    demo: 'https://jkmobile.vercel.app',
    image: '1706758311579jkombile.png',
    skills: ['js', 'react', 'redux', 'supabase'],
    made_at: '',
    year: 2023,
  },
  {
    id: 4,
    title: 'Kawi Admin Dashboard',
    description:
      'Developed the Kawi Admin Dashboard at Myanmar Media Linkage Company Limited in 2023.',
    demo: '',
    image: '1706757738516kawidashboard.png',
    skills: ['ts', 'nextjs', 'nodejs', 'expressjs'],
    made_at: 'Myanmar Media Linkage',
    year: 2023,
  },
  {
    id: 5,
    title: 'Javascript Questions',
    description: 'Javascript Questions Player',
    demo: 'https://jsquestionsr.vercel.app',
    image: '1706083427486javascript.png',
    skills: ['ts', 'nextjs', 'nodejs'],
    made_at: '',
    year: 2024,
  },
  {
    id: 6,
    title: 'MM Pad',
    description:
      'Developed the MMPad at Myanmar Media Linkage Company Limited in 2023.',
    demo: '',
    image: '1708971791352Screenshot from 2024-02-27 00-46-45.png',
    skills: ['ts', 'nextjs', 'nodejs'],
    made_at: 'Myanmar Media Linkage',
    year: 2023,
  },
  {
    id: 7,
    title: "Thihan's Portfolio",
    description: 'Developed a portfolio for Ko Thihan.',
    demo: 'https://thihan.vercel.app',
    image: '1710332392193Screenshot from 2024-03-13 18-33-59.png',
    skills: ['ts', 'nextjs', 'supabase'],
    made_at: 'Freelance',
    year: 2023,
  },
  {
    id: 8,
    title: 'IT Job MM',
    description: 'IT Job Finder Platform',
    demo: 'https://itjobmm.vercel.app',
    image: '1708972760498Screenshot from 2024-02-27 01-01-33.png',
    skills: ['ts', 'nextjs', 'nodejs', 'express', 'postgres'],
    made_at: '',
    year: 2024,
  },
  {
    id: 9,
    title: 'IT Job MM / Company Dashboard',
    description: 'Job Portal Company Dashboard',
    demo: 'https://itjobmm-company.vercel.app',
    image: '1710574614882Screenshot from 2024-03-16 14-03-11.png',
    skills: ['ts', 'nextjs', 'nodejs', 'express', 'postgres'],
    made_at: '',
    year: 2024,
  },
];
