export const projects = [
  {
    "id": 1,
    "title": "Edu Pad",
    "description": "Our ReactJS-powered Udemy-like platform offers dynamic interfaces and seamless user experiences, revolutionizing online learning with scalability and innovation.",
    "demo": "",
    "image": "1708015174003Screenshot from 2024-02-15 23-03-41.png",
    "skills": "Tailwindcss,FramerMotion,ReduxToolKit,React.js",
    "made_at": "Freelance",
    "year": 2023,
  },
  {
    "id": 19,
    "title": "Thihan's Portfolio",
    "description": "Developed a UI/UX project for Ko Thihan. The project aimed to briefly describe the project's goals and objectives, such as enhancing user experience or increasing engagement.",
    "demo": "https://thihan.vercel.app",
    "image": "1710332392193Screenshot from 2024-03-13 18-33-59.png",
    "skills": "Typescript,Tailwindcss,Next.js,Supabase",
    "made_at": "Freelance",
    "year": 2023,
  },
  {
    "id": 20,
    "title": "IT Job MM / Company Dashboard",
    "description": "Job Portal Company Dashboard, powered by Next.js, TypeScript, and NextUI. This dashboard offers a fast, user-friendly experience for managing job postings, tracking applicants, and gaining insights into your hiring process. With sleek design and customizable features, it's easy to use on any device. Plus, it's secure and supported by continuous updates. Simplify your recruitment efforts and elevate your hiring game with our dashboard",
    "demo": "https://itjobmm-company.vercel.app",
    "image": "1710574614882Screenshot from 2024-03-16 14-03-11.png",
    "skills": "Tailwindcss,NextUI,Typescript,Next.js",
    "made_at": "",
    "year": 2024,
  },
  {
    "id": 14,
    "title": "MM Pad",
    "description": "Developed the MMPad at Myanmar Media Linkage Company Limited in 2023. The project, built with Tailwindcss, RadixUI, NextJS, Zod, React-Hook-Form, Zustand, NextAuth, Inspired by Wattpad",
    "demo": "",
    "image": "1708971791352Screenshot from 2024-02-27 00-46-45.png",
    "skills": "Typescript,Next.js,NextAuth,Zod,React-Hook-Form,RadixUI",
    "made_at": "Myanmar Media Linkage",
    "year": 2023,
  },
  {
    "id": 17,
    "title": "IT Job MM",
    "description": "I spearheaded the development of a sophisticated IT job finder platform, employing a comprehensive tech stack comprising Next.js, Node.js, Express.js, MongoDB, TypeScript, and NextUI. Throughout the project lifecycle, I prioritized seamless user experiences and performance optimization, ensuring the platform's effectiveness in connecting job seekers with relevant opportunities in the IT sector.",
    "demo": "https://itjobmm.vercel.app",
    "image": "1708972760498Screenshot from 2024-02-27 01-01-33.png",
    "skills": "Typescript,Next.js,Node.js,Express.js,MongoDB,NextUI",
    "made_at": "",
    "year": 2024,
  },
  {
    "id": 7,
    "title": "Kawi Admin Dashboard",
    "description": "Developed the Kawi Admin Dashboard at Myanmar Media Linkage Company Limited in 2023. The project, built with Tailwind CSS, ShadcnUI, Next.js, Zod, and NextAuth, significantly improved internal management processes.",
    "demo": "",
    "image": "1706757738516kawidashboard.png",
    "skills": "Typescript,Next.js,NextAuth,Zod,React-Hook-Form,ShadcnUI",
    "made_at": "Myanmar Media Linkage",
    "year": 2023,
  },
  {
    "id": 3,
    "title": "JK Mobile",
    "description": "JK Mobile exemplifies my ability to leverage a diverse stack of technologies to create a refined and feature-rich mobile application. This project serves as a showcase of my expertise in front-end development, state management, and backend integration, making it a valuable addition to any resume",
    "demo": "https://jkmobile.vercel.app",
    "image": "1706758311579jkombile.png",
    "skills": "Tailwindcss,MaterialUI,React.js,ReduxToolkit,Supabase",
    "made_at": "",
    "year": 2023,
  },
  {
    "id": 2,
    "title": "SUPA Blog",
    "description": "This is created with tailwindcss, materialui, hyperui, reactjs and supabase. Supabase is firebase alternative. Supabase use relational database like postgresql.",
    "demo": "https://supablogr.vercel.app",
    "image": "1703784844823supablog.jpg",
    "skills": "Tailwindcss,MaterialUI,React.js,Supabase",
    "made_at": "",
    "year": 2023,
  },
  {
    "id": 8,
    "title": "Javascript Questions",
    "description": "This is created with shandui, mdx-remote, nextjs and nodejs.  This page is for javascript developer to practise easy the javascript. This questions got from Mrs.Lydia Hallie github.",
    "demo": "https://jsquestionsr.vercel.app",
    "image": "1706083427486javascript.png",
    "skills": "Typescript,ShadcnUI,Mdx-Remote,Next.js,Node.js",
    "made_at": "",
    "year": 2024,
  }
]