export const projects = [
  {
    id: 1,
    title: 'Edu Pad',
    description: 'Our ReactJS-powered Udemy-like platform',
    demo: '',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3',
    skills: ['js', 'react', 'redux', 'php', 'laravel', 'mysql'],
    made_at: 'Freelance',
    year: 2023,
  },
  {
    id: 2,
    title: 'SUPA Blog',
    description: 'Blogging Web Application with supabase',
    demo: 'https://supablogr.vercel.app',
    image: 'https://plus.unsplash.com/premium_photo-1665329006985-04f95dd59402',
    skills: ['js', 'react', 'redux', 'supabase'],
    made_at: '',
    year: 2023,
  },
  {
    id: 3,
    title: 'JK Mobile',
    description: 'Mini Mobile shop',
    demo: 'https://jkmobile.vercel.app',
    image: 'https://images.unsplash.com/photo-1512054502232-10a0a035d672',
    skills: ['js', 'react', 'redux', 'supabase'],
    made_at: '',
    year: 2023,
  },
  {
    id: 4,
    title: 'Kawi Admin Dashboard',
    description:
      'Developed the Kawi Admin Dashboard at Myanmar Media Linkage Company Limited in 2023.',
    demo: '',
    image: 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74',
    skills: ['ts', 'nextjs', 'nodejs', 'expressjs'],
    made_at: 'Myanmar Media Linkage',
    year: 2023,
  },
  {
    id: 5,
    title: 'Javascript Questions',
    description: 'Javascript Questions Player',
    demo: 'https://jsquestionsr.vercel.app',
    image: 'https://plus.unsplash.com/premium_photo-1661414473396-4600573d1f33',
    skills: ['ts', 'nextjs', 'nodejs'],
    made_at: '',
    year: 2024,
  },
  {
    id: 6,
    title: 'MM Pad',
    description:
      'Developed the MMPad at Myanmar Media Linkage Company Limited in 2023.',
    demo: '',
    image: 'https://images.unsplash.com/photo-1569098644584-210bcd375b59',
    skills: ['ts', 'nextjs', 'nodejs'],
    made_at: 'Myanmar Media Linkage',
    year: 2023,
  },
  {
    id: 7,
    title: "Thihan's Portfolio",
    description: 'Developed a portfolio for Ko Thihan.',
    demo: 'https://thihan.vercel.app',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8',
    skills: ['ts', 'nextjs', 'supabase'],
    made_at: 'Freelance',
    year: 2023,
  },
  {
    id: 8,
    title: 'IT Job MM',
    description: 'IT Job Finder Platform',
    demo: 'https://itjobmm.vercel.app',
    image: 'https://plus.unsplash.com/premium_photo-1661274189734-90d6aa7eb010',
    skills: ['ts', 'nextjs', 'nodejs', 'express', 'postgres'],
    made_at: '',
    year: 2024,
  },
  {
    id: 9,
    title: 'IT Job MM / Company Dashboard',
    description: 'Job Portal Company Dashboard',
    demo: 'https://itjobmm-company.vercel.app',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f',
    skills: ['ts', 'nextjs', 'nodejs', 'express', 'postgres'],
    made_at: '',
    year: 2024,
  },
];
