export const expConfig = [
  // {
  //   id: 1,
  //   title: 'Fullstack Developer',
  //   company: 'Freelance',
  //   description: 'I work at Freelance in Feb 1, 2023 as Full stack developer.',
  //   durationStart: 'Feb 2022',
  //   durationEnd: 'Present',
  //   logo: '/company/freelance.png',
  //   type: 'Freelance',
  // },
  {
    id: 2,
    title: 'Developer',
    company: 'Myanmar Media Linkage',
    companyLink: 'https://mml.com.mm/',
    description:
      'I work at Myanmar Media Linkage  in November 1, 2023 as Frontend developer.',
    durationStart: 'Nov 2023',
    durationEnd: 'March 2024',
    logo: '/company/mml.jpg',
    type: 'Onsite - Full-time',
  },
  {
    id: 4,
    title: 'Developer',
    company: 'SiThuLab',
    companyLink: 'https://www.sithucenter.com/',
    description:
      'I work at SiThu Computer Training Center  in August 1, 2024 as Web developer.',
    durationStart: 'May 2024',
    durationEnd: 'March 2025',
    logo: '/company/sithu.jpg',
    type: 'Onsite - Full-time',
  },
  {
    id: 5,
    title: 'Developer',
    company: 'BinaryHubz',
    companyLink: 'https://www.binaryhubz.com/',
    logo: '/company/binary.png',
    durationStart: 'Nov 2024',
    durationEnd: 'Present',
    type: 'Remote - Part-time',
  },
  {
    id: 6,
    title: 'Developer',
    company: 'MySOL',
    companyLink: 'https://www.mysoltech.com/',
    logo: '/company/mysol.png',
    durationStart: 'May 2025',
    durationEnd: 'Present',
    type: 'Onsite - Full-time',
  },
];
